version: "1"
services:
    webapp:
        build: .
        expose:
            - "5001"
            - "5000"
            - "443"
        ports:
        - 5000:5000
        - 5001:5001
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - DOTNET_URLS=https://*:5001;http://*:5000
        - ASPNETCORE_URLS=https://*:5001;http://*:5000
        - ASPNETCORE_Kestrel__Certificates__Default__Password=asdf123
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/App/aspnetapp.pfx